# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Francesco Fuggitti
author: Francesco Fuggitti
email: fuggitti@diag.uniroma1.it
description: #>- # this means to ignore newlines until "baseurl:"
  Francesco Fuggitti's personal website
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  francescofuggitti

institute1_name: Sapienza University
institute2_name: York University
# institute1_logo: sapienza-logo.png
# institute2_logo: york-logo.jpg
institute_logo: assets/university-logo.png
# institute_url: https://en.wikipedia.org/wiki/Mars_University



# Build settings
# theme: minima
markdown: kramdown
theme: academic-minima
# plugins:
#   - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

google_analytics: UA-137788077-3

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
